# Dependabot will run on day 20 of each month at 01:43 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
    assignees:
      - 'krobipd'
    versioning-strategy: 'increase'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'typescript'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'npm'
    directory: '/src-admin'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      timezone: 'Europe/Berlin'
    assignees:
      - 'krobipd'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '*'
    open-pull-requests-limit: 15

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
    assignees:
      - 'krobipd'
